### ISSUE TITLE
UpdateContact struct EmailBlacklisted impossible value false

### ISSUE THREAD

**Issue by ilyinstanislav** [getbrevo/brevo-go#10]
When i try to send EmailBlacklisted false i didnt get a correct result, because UpdateContact struct remove this param. 
The reason is omitempty for bool value.

just change 
`EmailBlacklisted bool 'json:"emailBlacklisted,omitempty"'`
on
`EmailBlacklisted bool 'json:"emailBlacklisted"'`

**Comment by ilyinstanislav** [comment]
The better way to fix this, is make it pointer 

`EmailBlacklisted *bool 'json:"emailBlacklisted,omitempty"'`

cause if not send this param the user set to black list

**Comment by jain-raunak** [comment]
Issue was already fixed, Thanks!
