### ISSUE TITLE
Validate Sender via OTP

### ISSUE THREAD

**Issue by DimoskiBojan** [getbrevo/brevo-go#15]
Validation of sender via OTP is not working, since the model is bad. 

Please change the model "model_otp.go" to use:
Otp int32 `json:"otp,omitempty"\`
instead of:
Name int32 `json:"name,omitempty"`

There is a PR for this already:
https://github.com/getbrevo/brevo-go/pull/14

**Comment by jain-raunak** [comment]
changes released, Thanks!
