### ISSUE TITLE
Cannot build package due to missing imports and type redeclarations

### ISSUE THREAD

**Issue by etabegro** [getbrevo/brevo-go#18]
There are multiple errors when trying to build the package:

```
github.com/getbrevo/brevo-go/lib
..\brevo-go\lib\api_master_account.go:2291:6: GetAccountActivityOpts redeclared in this block
	..\brevo-go\lib\api_account.go:153:6: other declaration of GetAccountActivityOpts
..\brevo-go\lib\model_configuration.go:14:6: Configuration redeclared in this block
	..\brevo-go\lib\configuration.go:53:6: other declaration of Configuration
..\brevo-go\lib\api_conversations.go:397:7: undefined: optional
..\brevo-go\lib\api_domains.go:175:13: undefined: optional
..\brevo-go\lib\api_inbound_parsing.go:38:107: undefined: os
..\brevo-go\lib\api_inbound_parsing.go:44:24: undefined: os
..\brevo-go\lib\api_inbound_parsing.go:129:11: undefined: os (exit status 1)
```

My thoughts:
- The redeclaration of `GetAccountActivityOpts` is not really a problem because the two definitions are equivalent. It is possible to just remove one of them.
- The missing import for `os` in `api_inbound_parsing` is also easy to fix - just add the import.
- The same is true for the missing import `optional`. We can just add the import of `github.com/antihax/optional`
- The redeclaration of `Configuration` is more problematic because the two types are actually different. As a quick fix it seems fine to move the `CustomSuccessUrl` Field from `model_configuration.go` to `configuration.go`. The `Configuration` type then becomes the following and we can delete the `model_configuration.go` file
```
type Configuration struct {
	BasePath         string            `json:"basePath,omitempty"`
	Host             string            `json:"host,omitempty"`
	Scheme           string            `json:"scheme,omitempty"`
	DefaultHeader    map[string]string `json:"defaultHeader,omitempty"`
	UserAgent        string            `json:"userAgent,omitempty"`
	CustomSuccessUrl string            `json:"customSuccessUrl"`
	HTTPClient       *http.Client
}
```

**Comment by odetolakehinde** [comment]
I agree.

**Comment by jain-raunak** [comment]
Its been released on production
